#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        0_Remove_node_from_gpfs_cluster
# Type:        Execute
# Script Type: Shell
# Description: Stop GPFS daemon and remove node from the cluster
# Script:

ssh @@{calm_array_address[0]}@@ 'source .bash_profile && sudo env "PATH=$PATH" mmshutdown -N @@{name}@@ && sudo env "PATH=$PATH" mmdelnode -N @@{name}@@'
