#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        5_Remove_node_from_gpfs_cluster
# Type:        Execute
# Script Type: Shell
# Description: Stop GPFS daemon and remove node from the cluster
# Script:

hn=$(hostname)
# If node is active in the cluster, stop the node and remove it from the cluster
# This allow to assume it's Scale In
source .bash_profile
if [ $(sudo env "PATH=$PATH" mmgetstate -N $hn | grep -c active) -eq 1 ]
then
  ssh @@{calm_array_address[0]}@@ 'source .bash_profile && sudo env "PATH=$PATH" mmshutdown -N @@{name}@@ && sudo env "PATH=$PATH" mmdelnode -N @@{name}@@'
fi
