#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        105_Start_GPFS_Cluster
# Type:        Execute
# Script Type: Shell
# Description: Create the GPFS Cluster

# Script:

set -e
source .bash_profile
if [ @@{calm_array_index}@@ -eq 0 ]
then
    i=$(sudo env "PATH=$PATH" mmgetstate -a | grep -c down)
    sudo env "PATH=$PATH" mmstartup -a
    sleep 1
    until [ $i -eq "0" ]
    do
        i=$(sudo env "PATH=$PATH" mmgetstate -a | grep -c arbitrating)
		echo "Arbitrating $i node(s)"
        sleep 2
    done
    echo "GPFS Daemon ready on all nodes"
fi
