#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        110_Create_GPFS_Volume_and_mount
# Type:        Execute
# Script Type: Shell
# Description: Create the GPFS volume and mount it
# Script:

set -e
if [ @@{calm_array_index}@@ -eq 0 ]
then
  sharedvg_vdisks="@@{sharedvg_vdisks}@@"

  # Add one UUID per line
  for uuid in $sharedvg_vdisks;do uuids=$"$uuids$uuid\n";done

  # Remove trailing empty line
  uuids=${uuids::-2}

  devs=$(lsblk -nodeps -no name,serial -PS /dev/sd* | grep -Ff <(echo -e $uuids) | cut -d\" -f2)
  touch NSD_Stanza_File.txt

  i=0
  for dev in $devs
  do
      i=$((i+1))
      echo "%nsd: device=$dev nsd=sasdata$i" | tee -a NSD_Stanza_File.txt
  done

  source .bash_profile
  sudo env "PATH=$PATH" mmcrnsd -F NSD_Stanza_File.txt
  sudo env "PATH=$PATH" mmcrfs sasdata -F NSD_Stanza_File.txt -B 1m
  sudo env "PATH=$PATH" mmmount sasdata /sasdata -a

fi
