#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        12_write_semaphore_file
# Type:        Execute
# Script Type: Shell
# Description: This script write a semaphore files on nodes spawn at 1st
#              launch. This allow to differentiate from scaled out nodes, i.e.
#              to update hosts file or sshd_config file
# Script:

# If the VM is vm0, create a semaphore file on all VMs. This will indicates
# these VMs were created during 1st blueprint launch
if [ @@{calm_array_index}@@ -eq 0 ]
then
  ips=$(echo @@{calm_array_address}@@ | sed 's/,/\ /g')

  # Create semaphore on all existing VMs from the calm_array
  for ip in $ips
  do
    ssh -o StrictHostKeyChecking=no $ip "mkdir changes;touch changes/semaphore"
  done
fi
