#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        20_Change_hostname
# Type:        Execute
# Script Type: Shell
# Description: Set the hostname to the Calm VM Name

# Script:

# Get name
hn="@@{name}@@"
# Lower case
hn="${hn,,}"

# Set hostname
sudo hostnamectl set-hostname $hn
