#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        40_Setup_SSH
# Type:        Execute
# Script Type: Shell
# Description: Configure SSH to secure access to the VM to users in the
#              specified group only, and prevent ssh root login except from
#              VMs deployed from the same blueprint

# Script:

set -ex

# Get appname and make it lower case
appname="@@{calm_application_name}@@"
appname="${appname,,}"

# Get list of IPs from hosts file
ad="$(cat /etc/hosts | grep $appname | cut -f1)"

# Replace space delimiter with comma delimiter
ad="$(echo $ad | sed 's/\ /,/g')"

# Create ssh group
sudo groupadd @@{sshgroup}@@
# For all machines, add centos to sshusers group
sudo usermod -aG @@{sshgroup}@@ @@{admin_cred.username}@@

# if first launch
# Disable ssh root login
sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config

# Disable ssh password authentication
sudo sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config

# Allow only members of ssh group to login using ssh
echo 'AllowGroups @@{sshgroup}@@' | sudo tee -a /etc/ssh/sshd_config

echo "Match Address $ad" | sudo tee -a /etc/ssh/sshd_config
echo "PermitRootLogin without-password" | sudo tee -a /etc/ssh/sshd_config
sudo service sshd restart


# If Scale out Replace Match Address directive and restart sshd

if ! [ -f /home/@@{admin_cred.username}@@/changes/semaphore ]
then
  for ip in $(cat /etc/hosts | grep $appname | cut -f1)
  do
    if ! [ $ip == "@@{address}@@"]
    then
      # Cannot be sudo ssh because at that stage, this host ip is NOT allowed by ssh
      # to connect with root over ssh. That is the purpose of below routine.
      ssh -o StrictHostKeyChecking=no $ip "sudo head -n -2 /etc/ssh/sshd_config > sshd_config.tmp && sudo mv sshd_config.tmp /etc/ssh/sshd_config"
      ssh -o StrictHostKeyChecking=no $ip "echo Match Address $ad | sudo tee -a /etc/ssh/sshd_config"
      ssh -o StrictHostKeyChecking=no $ip "echo PermitRootLogin without-password | sudo tee -a /etc/ssh/sshd_config"
      # restore sshd_config selinux permissions
      ssh -o StrictHostKeyChecking=no $ip "sudo /sbin/restorecon -v /etc/ssh/sshd_config"
      ssh -o StrictHostKeyChecking=no $ip "sudo service sshd restart"
    fi
  done
fi
