#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Action:      Create
# Name:        47_Download_Known_hosts_from_VM0
# Type:        Execute
# Script Type: Shell
# Description: Retrieve known_hosts from local user and root to this machine
# Script:

# Get appname and make it lower case
appname="@@{calm_application_name}@@"
appname="${appname,,}"

# get hostname
hn=$(hostname)

# Get hosts file from vm0
if ! [ @@{calm_array_index}@@ -eq 0 ]
then
    scp -o StrictHostKeyChecking=no @@{calm_array_address[0]}@@:.ssh/known_hosts ./.ssh/
    sudo cp .ssh/known_hosts /root/.ssh/known_hosts
fi

if ! [ -f /home/@@{admin_cred.username}@@/changes/semaphore ]
then
# If Scale out, connect to all and add new host except current VM and VM0
# update hosts in other VMs
  for ip in $(cat /etc/hosts | grep $appname | cut -f1)
  do
    case $ip in
      @@{calm_array_address[0]}@@|@@{address}@@)
        echo "No need to update this VM hosts file";;
      *)
      # Add to known_hosts with hostname
      ssh -o StrictHostKeyChecking=no $ip "echo -e '$(ssh-keyscan $hn)' | tee -a .ssh/known_hosts"
      ssh -o StrictHostKeyChecking=no $ip "echo -e '$(ssh-keyscan $hn)' | sudo tee -a /root/.ssh/known_hosts"

      # Add to known_hosts with ip address
      ssh -o StrictHostKeyChecking=no $ip "echo -e '$(ssh-keyscan @@{address}@@)' | tee -a .ssh/known_hosts"
      ssh -o StrictHostKeyChecking=no $ip "echo -e '$(ssh-keyscan @@{address}@@)' | sudo tee -a /root/.ssh/known_hosts"
    esac
  done
fi
